export const authActions = {
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    LOGOUT_TIMEOUT_SET: 'LOGOUT_TIMEOUT_SET',
};
